apiVersion: constraints.gatekeeper.sh/v1beta1
kind: DisablingDeletionProtectedNamespace
metadata:
  name: disablingdeletionprotectednamespace
spec:
  enforcementAction: warn
  match:
    kinds:
    - apiGroups:
      - ""
      kinds:
      - Namespace
